Allow additional arguments to ErrorHandler.lookup
getsentry/sentry-python pull request #1212
Opened 2021-10-02 21:05 UTC by ahopkins

This PR allows for Sanic v21.9 style error handlers to operate and provide full access to handling Blueprint specific error handlers.

---

> The ErrorHandler.lookup now requires two positional arguments:

[Source](https://sanicframework.org/en/guide/release-notes/v21.9.html#what-to-know)

See also: https://github.com/sanic-org/sanic/pull/2259

2021-10-02 21:53 UTC, prryplatypus approved these changes

2021-11-04 23:07 UTC, ahopkins commented
@AbhiPrasad So, I think this is generally a better approach. It will avoid touching `handle_request` which is really not a safe method to be monkeypatching. 

Instead, we monkeypatch the `_startup` method to inject some code into the request cycle using [signals](https://sanicframework.org/en/guide/advanced/signals.html#built-in-signals). You do not need to familiarize yourself too much with them other than to know it is a method to inject arbitrary code into the request/response cycle at predetermined points.

Locally all of the tests pass, except for `test_concurrency`. I think before I dig too deep into this to figure out why, it might be helpful if I understood some of this stuff:

```python
    weak_request = weakref.ref(request)
    request.ctx._sentry_hub = Hub(hub)
    request.ctx._sentry_hub.__enter__()

    with request.ctx._sentry_hub.configure_scope() as scope:
        scope.clear_breadcrumbs()
        scope.add_event_processor(_make_request_processor(weak_request))
```
```python
        with capture_internal_exceptions():
            with hub.configure_scope() as scope:
```

Any insight you could share?

2021-11-11 14:18 UTC, rhcarvalho requested changes
Thanks for the PR.

We have tried to focus on LTS versions as documented in https://docs.sentry.io/platforms/python/guides/sanic/.
We did merge in contributions to support recent non-LTS versions, but that's coming with a maintenance cost.

I'm happy we take this in to unblock users, but would also like to strongly consider dropping support for the non-LTS releases once 21.12 is out. Would that be a fair ask?

2021-11-11 18:07 UTC, ahopkins commented
That is a contract between you and your user base. I'm happy to make this PR to help out and/or be a resource as needed.

2021-11-11 19:07 UTC, ahopkins commented on sentry_sdk/integrations/sanic.py
> +        global version
Are you okay with it being a class attribute?

2021-11-15 14:04 UTC, AbhiPrasad approved these changes

2021-11-15 19:06 UTC, ahopkins commented on sentry_sdk/integrations/sanic.py
> +    version: Tuple[int, ...] = (0, 0)
Just pushed a commit to move it to a comment

2021-11-15 19:16 UTC, AbhiPrasad commented on sentry_sdk/integrations/sanic.py
> +    version: Tuple[int, ...] = (0, 0)
Yeah we have `2.7` code that we have to support, so the codebase mainly leverages mypy comments for typing with a few exceptions.

Looking forward when we can rm -rf that, but will take a bit so we don't break users.

2021-11-16 14:28 UTC, merged

2021-11-16 14:28 UTC, AbhiPrasad commented
Thank you for your contribution @ahopkins!