feat(huey): add Huey Integration
getsentry/sentry-python pull request #1555
Opened 2022-08-10 17:29 UTC by Zhenay

See #195

2022-11-07 13:53 UTC, antonpirker commented
Hey @Zhenay !
We are done reviewing a PyMongo integration and now is the time for Huey! 
I will probably have a look at this later this week

2022-11-08 02:39 UTC, j-krl commented
Looking forward to using this!

2022-11-10 13:24 UTC, antonpirker approved these changes
Just some cosmetic changes. If those are made and all the tests are green I will create a sample huey setup and give it a spin. (Tomorrow Friday, I am not in front of a computer, so I will be back here on Monday)

2022-11-10 13:24 UTC, antonpirker commented on sentry_sdk/integrations/huey.py
> +                op="huey.task",
Please change the `op` to be `queue.task.huey`. (see documentation here: https://develop.sentry.dev/sdk/performance/span-operations/)

2022-11-10 13:24 UTC, antonpirker commented on sentry_sdk/integrations/huey.py
> +        mechanism={"type": "huey", "handled": False},
Please use here `HueyIntegration.identifier` for setting the type

2022-11-10 13:24 UTC, antonpirker commented on sentry_sdk/integrations/huey.py
> +                op="huey.task",
Oh and please add `OP.QUEUE_TASK_HUEY` constant here: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/consts.py#L110 and then use the constant.

2022-11-10 13:24 UTC, antonpirker commented on sentry_sdk/integrations/huey.py
> +        with hub.start_span(op="huey.enqueue", description=task.name):
Oh and please add `OP.QUEUE_SUBMIT_HUEY` constant (set to "queue.submit.huey") here: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/consts.py#L110 and then use the constant.

2022-11-10 13:24 UTC, antonpirker commented on tests/integrations/huey/test_huey.py
> +    assert event["spans"][0]["op"] == "huey.enqueue"
Please keep this a string and do not use the constants (mentioned above) in the tests. This way they tests will fail when the string of the constant changes.

2022-11-10 13:26 UTC, antonpirker requested changes
Before I clicked wrong. So please make the changes mentioned in the comments in the PR. 

When the changes are made and all the tests are green I will setup a sample huey project and give it a spin. 
(I am not in front of a keyboard tomorrow (Friday) so I will be back here on Monday.)

2022-11-18 08:39 UTC, Zhenay commented
Hey @antonpirker 
Could you please run the workflow

2023-01-25 12:18 UTC, antonpirker commented
Hey @Zhenay ! I have now set up a simple demo app and everything looks good.

I have the spans for the enqueuing/submitting of tasks:
![Screenshot 2023-01-25 at 13 09 38](https://user-images.githubusercontent.com/202325/214561068-c0985b77-1870-4dd9-8ca5-18f3a69a1d8a.png)

And also the span for the task itself
![Screenshot 2023-01-25 at 13 10 08](https://user-images.githubusercontent.com/202325/214561102-838dd113-689f-4e04-870f-4a00810320a3.png)

I added a little check in your branch to only send sensitive date (the arguments and kwargs of the task) when the option "send_default_pii" is set to true. Because there could be all sorts of sensitive data (passwords, email adresses, names, ... in there) and this data should never be sent by default.

2023-01-25 12:24 UTC, antonpirker approved these changes

2023-01-25 12:37 UTC, antonpirker commented
Hey @Zhenay !
Great work, everything looks good. 

In your opinion, is this ready to be merged and shipped?
When there are some bug reports, will you be able to address them?

FYI: The next release will be in around 2 weeks or so.

Oh, and if you send me your shipping address (and t-shirt size) I can see If I can send you some swag as a little thank you. (send it to anton,pirker@sentry.io)

2023-01-25 12:49 UTC, Zhenay commented
Hey, @antonpirker!
Thanks for your attention.

I suppose it can be merged. If any bugs are reported, I will be glad to fix them.

2023-01-25 15:41 UTC, merged

2023-01-25 15:41 UTC, antonpirker commented
Here you go! Thanks again!

2023-02-13 15:32 UTC, ulgens commented
I couldn't find any reference to huey under https://docs.sentry.io/platforms/python/guides/django/configuration/integrations/, is it normal?

2023-07-07 14:36 UTC, nick4333 commented
Are there any plans to update the documentation to include a huey integration?

2023-10-11 10:48 UTC, sentrivana commented
Hey @ulgens, @nick4333, sorry for the late reply, I've created an issue for the missing docs https://github.com/getsentry/sentry-python/issues/2436 and we'll add them shortly!