Faster Tests (DjangoCon)
getsentry/sentry-python pull request #1602
Opened 2022-09-06 11:44 UTC by antonpirker

This fixes #1499 

* Trying the sentry-ruby way (splitting up into multiple yaml files, this works great. I have created a script to split tox.ini into multiple yaml files automatically)
* Trying tox-gh (does not help us, because we already have this paralleization in GitHub actions)
* Cleaning up the yaml file in general.
* Using a RAM drive for the tox virtualenvs in the GitHub runners
* Removed PyPy from the test suite because it was never run. We have to reevaluate support for PyPy.

2022-09-16 12:19 UTC, antonpirker commented on tox.ini
> +    py.test --durations=5 {env:TESTPATH} {posargs}
This is for showing the 5 slowest tests at the bottom of the log output

2022-09-16 13:04 UTC, sl0thentr0py requested changes
ok firstly, great work!
just some random comments and one more here.

Can you document in the PR description / contributing guide what we need to do if we add/remove a certain tox configuration in `tox.ini`? (basically just run the script again, I guess.)

2022-09-16 13:09 UTC, antonpirker commented on tox.ini
> +toxworkdir=~/toxworkdir/.tox
That's the RAM drive. But I guess I can just change it to be in the default location (because ram drive creation is only happening in CI anyhow)

2022-09-19 08:54 UTC, antonpirker commented on .github/workflows/test-common.yml
> +          coverage combine .coverage*
Yes, we do not look at the reports anyhow.
I will keep them for now, but have created an issue for reevaluating this: https://github.com/getsentry/sentry-python/issues/1628

2022-09-19 10:46 UTC, sl0thentr0py approved these changes
:shipit:

2022-09-19 13:06 UTC, antonpirker commented
I have now made it so the CI fails when `tox.ini` and the existing yaml files are out of sync: https://github.com/getsentry/sentry-python/actions/runs/3082611176/jobs/4982524192

2022-09-19 14:40 UTC, merged