feat(integrations): Add method and path pattern transaction style for the Django integration
getsentry/sentry-python pull request #1810
Opened 2022-12-27 21:03 UTC by rynmlng

The method and path pattern for transaction styles includes the HTTP method as well as request path. This new transaction style for Django allows events to be grouped by this segmentation.

2023-01-11 15:52 UTC, rynmlng commented
@antonpirker how can I help move this forward?

2023-01-17 09:29 UTC, antonpirker requested changes

2023-01-17 09:29 UTC, antonpirker commented on sentry_sdk/integrations/django/__init__.py
> +TRANSACTION_STYLE_VALUES = ("function_name", "method_and_path_pattern", "url")
Please call it "url_with_method" so we see it is related to "url".

2023-01-17 09:34 UTC, antonpirker commented
Hey @rynmlng thanks for the contribution! 

Sorry for the delay, but we have kind of a lot on our plates right now.

2023-01-17 10:36 UTC, antonpirker commented
Hey @rynmlng !
I had a look at your contribution, and I am afraid I can not merge this. This adds to much overhead in maintaining and also maintaining the documentation.

But there is a solution for your problem, you can add the method in a `before_send` hook. Something like this:

```python
import sentry_sdk

def add_method_to_transaction_name(event, hint):
    # modify event here
    event["transaction"] = f"{event["request"]['method']} {event["transaction"]}"
    return event

sentry_sdk.init(
    dsn="...",
    before_send=add_method_to_transaction_name,
)
```

2023-01-17 10:37 UTC, closed without merging

2023-01-17 12:07 UTC, antonpirker commented
The solution above is for error events. (And there is a small bug `"request"` in the f-string should be `'request'`.

2023-01-17 12:14 UTC, antonpirker commented
If you want to change the transaction name for all kind of events (errors and transactions (the stuff ending up in the "performance" main menu item on sentry.io)) you can write an `event_processor`.

This is a little bit more complicated, because you first have to fetch the HTTP method in a Django middleware because the `event_processor` has no access to the Django request:

1: Middleware to save the http method:

```python
# middleware.py
import sentry_sdk

def sentry_middleware(get_response):
    def middleware(request):
        with sentry_sdk.configure_scope() as scope:
            # Saving HTTP method into Sentry scope
            scope.set_extra("http_method", request.method)
        
        response = get_response(request)
        return response

    return middleware
```

2. Add the event processor:
```python
sentry_sdk.init(
    dsn="...",
)

def make_nice_transaction_name(event, hint):
    # Get HTTP method from Sentry scope
    event["transaction"] = f"{event['extra']['http_method']} {event['transaction']}"
    return event

with sentry_sdk.configure_scope() as scope:
    scope.add_event_processor(make_nice_transaction_name)
```

2023-01-17 12:15 UTC, antonpirker commented
Hope this helps!