Draft: Add integerations for socket and grpc
getsentry/sentry-python pull request #1911
Opened 2023-02-18 13:33 UTC by Hossain-raeisi

2023-02-20 19:20 UTC, Hossain-raeisi commented
docs [pull request](https://github.com/getsentry/sentry-docs/pull/6327)

2023-02-20 19:23 UTC, Hossain-raeisi commented
I think this merge request has reached a stable state, would appreciate a review @sl0thentr0py  @antonpirker

2023-02-22 15:54 UTC, sl0thentr0py commented
ty so much for the contribution @Hossain-raeisi , we'll try to get to this next week

2023-02-22 20:17 UTC, antonpirker commented
Hey @Hossain-raeisi 
Amazing contribution! As @sl0thentr0py said we will have a look next week, we are already very stoked about this!

2023-02-28 13:41 UTC, Hossain-raeisi commented
Hey!
Any updates @sl0thentr0py @antonpirker ?

2023-02-28 14:59 UTC, antonpirker commented
Have not had time yet. Please hang in there.

2023-03-03 08:51 UTC, antonpirker commented
Hey @Hossain-raeisi !
At first glance it looks good.
I fixed some smaller things to make CI happy. 

Still, there are some errors in CI mostly about typing:
https://github.com/getsentry/sentry-python/actions/runs/4321738769/jobs/7543323597

Could you fix them?
(Ignore the gevent errors, I have to fix those)

2023-03-04 20:39 UTC, Hossain-raeisi commented
Hi @antonpirker 
thanks for the review 
I made some changes and hopefully they should solve most of the errors, but I dont think I can do anything about these ones 
https://github.com/getsentry/sentry-python/actions/runs/4321738769/jobs/7543323597#step:4:81

2023-03-13 20:31 UTC, Hossain-raeisi commented
Hey @antonpirker!
do you have any free time in next few days to pair and finish up this pr?

2023-03-28 11:49 UTC, antonpirker requested changes

2023-03-28 15:11 UTC, antonpirker commented on sentry_sdk/integrations/grpc/server.py
> +            name = self._find_method_name(context)
I have now added a small fix to your PR concerning the `_find_method_name` function. @Oogwey can you check if this is what you wanted to do?

2023-03-28 15:12 UTC, antonpirker commented
I created a small demo project and the traces are propagated perfectly! Really cool!

![Screenshot 2023-03-28 at 17 11 33](https://user-images.githubusercontent.com/202325/228283964-561bbd22-6dfb-4179-88d8-bfde3c950d09.png)

2023-03-28 15:13 UTC, antonpirker approved these changes

2023-03-28 15:14 UTC, antonpirker commented
I guess when you @Oogwey are ok with the changes that I did in your PR, then we can merge this!

2023-03-28 15:17 UTC, antonpirker commented
oh, and we have to fix the typing errors. I will look at this tomorrow!

2023-03-28 16:27 UTC, Oogwey commented
> I guess when you @Oogwey are ok with the changes that I did in your PR, then we can merge this!

changes seem alright to me, thanks

2023-03-29 11:02 UTC, antonpirker commented
I changed now the setup, that GRPC tests are only run in Python 3.7+ (because the protobuffers in the tests did not work with version installed on older pythons)

Is this fine with you @Oogwey ?

2023-03-29 16:30 UTC, Oogwey commented
> I changed now the setup, that GRPC tests are only run in Python 3.7+ (because the protobuffers in the tests did not work with version installed on older pythons)
> 
> Is this fine with you @Oogwey ?
alright with me :+1:

2023-03-29 16:46 UTC, Oogwey commented
> I have one more ask @Oogwey , could you please rename `TestService`, `TestMessage` and `test_grpc_server` and prefix it with something like `Grpc` or whatever. Pytest it trying to collect tests from all files prefixed `test_` and all classes prefixed `Test` so pytest struggles with out code. Thank You!

Done!

2023-03-30 10:13 UTC, antonpirker commented
I am not sure why the Python 2.7 tests are suddenly failing, because those are tests you and me did not touch. 🤷 Very strange. (thought it is because of a file called `socket.py`, but there are other things also failing...

Could you please merge the newest `master` from `getsentry/sentry-python` into your branch (or rebase yours on top of it?) Maybe this helps. Thanks @hossein-raeisi

2023-03-30 10:53 UTC, hossein-raeisi commented
> I am not sure why the Python 2.7 tests are suddenly failing, because those are tests you and me did not touch. shrug Very strange. (thought it is because of a file called `socket.py`, but there are other things also failing...
> 
> Could you please merge the newest `master` from `getsentry/sentry-python` into your branch (or rebase yours on top of it?) Maybe this helps. Thanks @hossein-raeisi


strange :thinking: 
seems like is already merged:
![image](https://user-images.githubusercontent.com/93824777/228814281-475eeac5-b993-4f41-923c-2cf0b838199f.png)
(remote sentry refers to getsentry/sentry-python)

2023-03-30 11:58 UTC, antonpirker commented
Hm. Now all the tests pass. I guess it was a GitHub hiccup, because they had problems with Github actions in the last couple of days.

2023-03-30 11:59 UTC, merged

2023-03-30 12:39 UTC, hossein-raeisi commented
> Congrats and thanks for you patience @hossein-raeisi !
> 
> Really great contribution! Thank you so much! We will release this in the next couple of days.
> 
> If you would like a little thank you gift please send me your shipping address and t-shirt size to [anton.pirker@sentry.io](mailto:anton.pirker@sentry.io)

thanks, I would love that

2023-04-04 12:02 UTC, antonpirker commented
Your contributions have been released @hossein-raeisi : https://github.com/getsentry/sentry-python/releases/tag/1.19.0