Work with a copy of request, vars in the event
getsentry/sentry-python pull request #2125
Opened 2023-05-19 13:16 UTC by sentrivana

In some cases we were attaching parts of the original request to the event with live references on it and ending up modifying the underlying headers or request data when we scrubbed the event. Now we make sure to only attach a copy of the request to the event. We also do the same for frame vars.

See:
- https://github.com/getsentry/sentry-python/issues/2109
- https://github.com/getsentry/sentry-python/issues/2114

2023-05-19 13:17 UTC, sentrivana commented on sentry_sdk/integrations/_wsgi_common.py
> +            request_info["cookies"] = self.cookies()
`self.cookies()` here should always already be a `dict` and there is no need to copy it twice now that we `deepcopy` the whole request a bit further down.

2023-05-22 09:36 UTC, sl0thentr0py approved these changes

2023-05-22 09:38 UTC, sl0thentr0py requested changes
need to do this in all of these 
```bash
➜  sentry-python git:(master) rg 'event.*"request".*=' sentry_sdk
sentry_sdk/integrations/gcp.py
196:        event["request"] = request

sentry_sdk/integrations/asgi.py
214:        event["request"] = request_info

sentry_sdk/integrations/_wsgi_common.py
80:        event["request"] = request_info

sentry_sdk/integrations/aws_lambda.py
383:        sentry_event["request"] = request

sentry_sdk/integrations/fastapi.py
119:                        event["request"] = request_info

sentry_sdk/integrations/starlette.py
392:                            event["request"] = request_info
438:                            event["request"] = request_info
```

2023-05-22 14:22 UTC, sl0thentr0py approved these changes

2023-05-22 14:38 UTC, merged