Revert "Pin urllib3 to <2.0.0 for now"
getsentry/sentry-python pull request #2148
Opened 2023-05-31 18:54 UTC by asottile-sentry

Reverts getsentry/sentry-python#2069

Resolves #2070

this shouldn't have been pinned in the first place.  the actual failure was unrelated to sentry.  _they_ should have pinned in their app -- a library should not make this decision for its users

2023-05-31 19:57 UTC, sl0thentr0py commented
there is more complexity to the discussion and an open PR at https://github.com/getsentry/sentry-python/pull/2137
I was OOO, we will release this soon, closing.

2023-05-31 20:03 UTC, asottile-sentry commented
that PR is based on an incorrect assumption and does not include the necessary fixes to typing, docs, etc.

2023-06-01 11:15 UTC, sentrivana requested changes
See comment, otherwise LGTM.

2023-06-01 13:03 UTC, asottile-sentry commented on sentry_sdk/transport.py
> +        # type: (urllib3.BaseHTTPResponse) -> None
this is only used in a type comment and has no effect on the runtime nor compatibility

2023-06-01 13:27 UTC, asottile-sentry commented on sentry_sdk/transport.py
> +        # type: (urllib3.BaseHTTPResponse) -> None
additionally the type checker will not understand the `try` / `except` pattern:

```
pip install mypy types-urllib3 'urllib3<2'
```

```console
$ cat t.py 
try:
    from urllib3 import BaseHTTPResponse as Response
except ImportError:
    from urllib3 import HTTPResponse as Response


reveal_type(Response)
$ mypy t.py
t.py:2: error: Module "urllib3" has no attribute "BaseHTTPResponse"; maybe "HTTPResponse"?  [attr-defined]
t.py:7: note: Revealed type is "Any"
Found 1 error in 1 file (checked 1 source file)
```

2023-06-02 07:00 UTC, sentrivana approved these changes

2023-06-02 07:07 UTC, merged