Master
getsentry/sentry-python pull request #2193
Opened 2023-06-23 15:39 UTC by nicolassanmar

2023-06-26 07:41 UTC, sentrivana requested changes
@nicolassanmar Thanks a ton for this PR! The change looks good, left a small comment. Could you please also add a testcase or two for this?

2023-06-26 07:41 UTC, sentrivana commented on sentry_sdk/utils.py
> +            or getattr(exc_value, "detail", "")
Let's be safe, just in case:
```suggestion
            or safe_str(getattr(exc_value, "detail", ""))
```

2023-07-03 14:11 UTC, nicolassanmar commented
> @nicolassanmar Thanks a ton for this PR! The change looks good, left a small comment. Could you please also add a testcase or two for this?

Sure, been busy this week, but I will update this when I can

2023-08-06 14:27 UTC, goharShoukat commented
> > @nicolassanmar Thanks a ton for this PR! The change looks good, left a small comment. Could you please also add a testcase or two for this?
> 
> Sure, been busy this week, but I will update this when I can

@sentrivana I have added test to this PR. 

For some reason, the new commit doesn't show up here and shows on a new branch. 
https://github.com/getsentry/sentry-python/pull/2294

2023-08-07 08:01 UTC, sentrivana commented
Thanks @goharShoukat! I'll take a look sometime this week.

2023-08-10 10:51 UTC, sentrivana approved these changes

2023-08-10 10:51 UTC, merged

2023-08-10 10:51 UTC, sentrivana commented
@nicolassanmar @goharShoukat Thank you both!

2023-08-10 10:53 UTC, goharShoukat commented
> 

Been following the changes you made Ivana. I had a question. The tests I wrote worked in Python 3.10. Is the attempt here to make the code backward compatible too? 

This is my first every open-source contribution, albeit a very small one, I am still quite proud to make it. Looking forward to contributing in the future.

2023-08-10 11:08 UTC, sentrivana commented
@goharShoukat It's a great first contribution! Congrats! :)

The change I made to the test had to do with the change I made to the behavior of the `get_error_message` function (this line specifically https://github.com/getsentry/sentry-python/pull/2193/files#diff-e9f88ca6368ce622839e078ed26c741a927752c01ceae64cd504d3ae86de6fd2R689). Before this PR, we were falling back to `safe_str(exc_value)` in case we didn't succeed in getting the `message` attribute, but in the previous version of this PR we would just return an empty string if we didn't find neither `message` nor `detail`, which would have been a breaking change from before. I then had to adjust the test to also check that the fallback is `safe_str(exc_value)` and not an empty string.

Hope that makes sense. Looking forward to more contributions from you in the future!