Add wrapper for `Celery().send_task` to support behavior as `Task.apply_async`
getsentry/sentry-python pull request #2377
Opened 2023-09-16 11:39 UTC by Divaltor

…ly_async`

2023-10-22 14:17 UTC, Divaltor commented
Any review?

2024-01-24 11:16 UTC, sentrivana requested changes
Hey @divaltor, thanks for the PR and sorry for taking so long to review this. The change looks good to me in general. Could you additionally:
* rebase on/merge current `master` into your branch, there's a conflict that needs resolving
* address the comments I left on the PR

Thanks again! If you don't have the time we're also happy to take it from here and push this over the finish line.

2024-01-24 11:16 UTC, sentrivana commented on sentry_sdk/integrations/celery.py
> +        Celery.send_task = _wrap_apply_async(Celery.send_task)
Can we rename the wrapper to something else now that we're not just using it to wrap `apply_async`? Something more generic, maybe `_wrap_run_task`?

2024-01-24 11:16 UTC, sentrivana commented on tests/integrations/celery/test_celery.py
It'd be great to test the `send_task` wrapping more thoroughly with more test cases rather than just the one -- can you add it to the `celery_invocation` fixture?

2024-01-24 17:33 UTC, divaltor commented on tests/integrations/celery/test_celery.py
The problem with passing `Celery` instance to that fixture is that we need to create whole worker with some "real" one backend like Redis, because `Celery.send_task` ignores configuration for eager tasks
<img width="622" alt="image" src="https://github.com/getsentry/sentry-python/assets/29837527/8d40bc71-4b77-4b64-a3b4-64b21074abfd">

I think it possible to add that to `celery_invocation`, but it'll increase tests duration because we need to create "real" instance almost each run

2024-01-25 11:13 UTC, sentrivana commented on tests/integrations/celery/test_celery.py
Gotcha. Do we know how much it would slow down the tests? I'd definitely prefer if we could run all of the existing tests where we test `apply_async` with `send_task` as well since that way we'd be able to catch regressions if there's a change in Celery upstream that only affects `send_task` but not `apply_async`. Unless this makes the tests horrifically slow.

2024-01-25 15:19 UTC, divaltor commented on tests/integrations/celery/test_celery.py
I'll try to implement that and response if it'll be a lot slower than now

2024-01-31 21:07 UTC, divaltor commented on tests/integrations/celery/test_celery.py
@sentrivana Sorry for bothering you. Tried to refactor that thing, but it took more time and effort than it was look. Unfortunately, I don't have much time to make that thing done, so I'm really feel sorry that I can't complete it right now

If you want - you can take this branch as is and work on it, if you think you have resources for that, thanks for understanding 😞

2024-02-01 08:49 UTC, sentrivana commented on tests/integrations/celery/test_celery.py
Hey @divaltor, thanks a ton for your work on this so far! I understand of course -- no worries, we can take it from here. :)

2024-09-03 11:20 UTC, sentrivana approved these changes
Once CI on master is green, we can merge this

2024-09-04 08:08 UTC, merged