feat(integrations): Add Anthropic Integration
getsentry/sentry-python pull request #2831
Opened 2024-03-16 18:22 UTC by czyber

This PR adds an anthropic integration. It supports the creation of messages in streaming and non-streaming mode.
It is heavily inspired/analogous to the OpenAI integration. 

---

## General Notes

Thank you for contributing to `sentry-python`!

Please add tests to validate your changes, and lint your code using `tox -e linters`.

Running the test suite on your PR might require maintainer approval. Some tests (AWS Lambda) additionally require a maintainer to add a special label to run and will fail if the label is not present.

#### For maintainers

Sensitive test suites require maintainer review to ensure that tests do not compromise our secrets. This review must be repeated after any code revisions.

Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before running sensitive tests.

2024-04-25 13:08 UTC, antonpirker commented
Hey @czyber !

Thanks for this great PR! 
As we released a big update to our SDK today, some of your code is broken!
I will allow myself to update your code to work with the new 2.0 version of the SDK.

2024-04-25 13:58 UTC, antonpirker commented
Hey again @czyber , 

I made some changes to better deal with the spans. Everything looks great!

One question: Do the test actual send data to Anthropic? Or does the "z" api_key enable some sort of test mode? (because we do not want to access the internet in our tests, if it is not absolutely necessary)

2024-04-25 17:21 UTC, czyber commented
Hey @antonpirker,

Thank you for updating the PR! 

The test do not send data to Anthropic, yet initializing the client with `api_key="z"` does not enable some kind of test mode, it does not send a request. Also, i mocked the part where requests would actually be sent (the `_post` attribute of `SyncAPIResource`)

2024-04-26 09:12 UTC, antonpirker approved these changes
This looks good! Thanks again for the contribution!

I will hold on merging this for a bit, because we released 2.0 yesterday and maybe we need to do some hot fixes. 

We also have a Langchain integration in the works right now, and I would like to release both in the same version, so we have a kind of AI update :-)

2024-04-26 21:36 UTC, colin-sentry requested changes
A few changes needed after langchain is merged, but this looks good otherwise. Nice work :)

2024-04-26 21:36 UTC, colin-sentry commented on sentry_sdk/integrations/anthropic.py
> +        span.set_data(COMPLETION_TOKENS_USED, output_tokens)
Once langchain is merged, this should use the new helper function https://github.com/getsentry/sentry-python/pull/2911/files#diff-c566959db6701d8426b02bcf30caa0222d01aa9931ce9913b1a35fedfd0953c1R59

2024-04-26 21:36 UTC, colin-sentry commented on sentry_sdk/integrations/anthropic.py
> +            span.set_data("ai.streaming", False)
It'd be nice to pull the tags we have in langchain too if any exist in the params: https://github.com/getsentry/sentry-python/pull/2911/files#diff-bba846cf7b623cb617bd628d482cd71fe41160f0cea1f48f321fcf5166472925R52-R62

2024-04-26 21:36 UTC, colin-sentry commented on sentry_sdk/integrations/anthropic.py
> +                        span.set_data(TOTAL_TOKENS_USED, input_tokens + output_tokens)
New helper function again (after langchain merged)

2024-04-26 21:36 UTC, colin-sentry commented on tests/integrations/anthropic/test_anthropic.py
> +    assert span["data"][PROMPT_TOKENS_USED] == 10
Some of this has changed a bit in the langchain merge as well, it's span["measurements"] I believe

2024-04-28 09:09 UTC, czyber commented
Hey @colin-sentry ,
thanks for the review!

I have the langchain PR on my mind, and will incorporate the requested changes as soon as it is merged 👍

2024-04-30 14:28 UTC, antonpirker commented
fyi @czyber the langchain branch has been merged into master!

2024-05-01 07:48 UTC, czyber commented
fyi @colin-sentry @antonpirker , I updated the PR to use the shared functionality for AI integrations that was introduced in the langchain integration PR.

2024-05-01 14:06 UTC, colin-sentry approved these changes
Looks good to me! Nice work.

2024-05-02 11:11 UTC, antonpirker commented
Yes! Great work everybody! Thanks a lot!

2024-05-02 11:12 UTC, merged