Fix `data` in clickhouse-driver integration
getsentry/sentry-python pull request #3638
Opened 2024-10-09 12:35 UTC by sentrivana

2024-10-09 12:39 UTC, sentrivana commented on sentry_sdk/integrations/clickhouse_driver.py
> +        span.set_data("db.query.text", query)
https://opentelemetry.io/docs/specs/semconv/database/database-spans/#common-attributes

2024-10-09 13:13 UTC, sl0thentr0py requested changes

2024-10-09 13:13 UTC, sl0thentr0py commented on sentry_sdk/integrations/clickhouse_driver.py
> +                query = span._get_attribute("db.query.text")
If we need to access attributes outside, let's officially expose `get_attributes` or a `@property` called `attributes`. Accessing underscore methods outside the implementation is an anti-pattern and we should stop doing that.

2024-10-10 08:10 UTC, sentrivana commented on sentry_sdk/integrations/clickhouse_driver.py
> +                span.set_attribute("db.params", json.dumps(db_params))
Moved it to the `connection`.

2024-10-10 12:00 UTC, sl0thentr0py approved these changes

2024-10-10 13:40 UTC, merged