Sample on root span level
getsentry/sentry-python pull request #3767
Opened 2024-11-13 09:10 UTC by sentrivana

Closes https://github.com/getsentry/sentry-python/issues/3766

2024-11-13 09:26 UTC, sentrivana commented on sentry_sdk/tracing.py
> +        parent_sampled=None,  # type: Optional[bool]
Not sure if we want to continue supporting this arg, but added it for now

2024-11-13 14:34 UTC, sentrivana commented on sentry_sdk/integrations/opentelemetry/sampler.py
> +        parent_sampled = attributes.get(SentrySpanAttribute.CUSTOM_PARENT_SAMPLED)
removed altogether

2024-11-13 14:34 UTC, sentrivana commented
@sl0thentr0py Removed `parent_sampled` and updated the tests a bit more, please recheck

2024-11-14 10:36 UTC, sl0thentr0py requested changes

2024-11-14 10:36 UTC, sl0thentr0py commented on tests/tracing/test_sampling.py
> +        with start_span(name="catpark", sampled=parent_sampling_decision):
this test should mirror the one above  where you added the continue_trace

2024-11-14 10:57 UTC, sl0thentr0py approved these changes

2024-11-14 10:58 UTC, merged