Fix lru cache copying
getsentry/sentry-python pull request #3883
Opened 2024-12-18 23:44 UTC by ffelixg

This addresses the lru cache copy function by walking the circularly linked list and creating new cache/root attributes instead of using (deep-)copy on the source.

Fixes #3852

2024-12-19 12:43 UTC, antonpirker reviewed
This looks good to me. Because it is some tricky code, I will ask for some other engineers to review it before I will merge it.

2024-12-19 14:10 UTC, cmanallen requested changes
@ffelixg Thanks for your interest in fixing this bug!  I left some review comments.  You can also review my PR here to see how I implemented it: https://github.com/getsentry/sentry-python/pull/3882/files.  Obviously I'm biased in favor of my solution to the problem but you're welcome to let me know where I've made short comings!

2024-12-19 15:31 UTC, cmanallen commented on sentry_sdk/_lru_cache.py
> +        while node is not self.root:
Anthony's suggested LRU would fix this issue.

2024-12-19 16:50 UTC, ffelixg commented on sentry_sdk/_lru_cache.py
> +        return lru_cache
Thanks for the review. I was working under the assumption that the correct behavior for `cache.__copy__()` or `copy(cache)` is to return a shallow copy of the cache, like it does for lists etc. So it was my intention that things like `test_mutable` fail.

I'm not sure in which context this is used, so I don't know if shallow or deep is more useful. Maybe there should be a separate __deepcopy__ method?

2024-12-19 16:59 UTC, cmanallen commented on sentry_sdk/_lru_cache.py
> +        return lru_cache
No worries I can understand where that assumption came from.  The correct behavior is a deepcopy.  The shallowcopy was a mistake I introduced in a rush.

> I'm not sure in which context this is used,

Its a helper utility so we can assume its use in any context.  That's why I removed the __copy__ methods in my PR.

2024-12-20 11:31 UTC, antonpirker approved these changes
After a quick discussion here https://github.com/getsentry/sentry-python/issues/3852 we will settle on a simpler lru cache implementation. 

This looks fine now and has all the tests, so it is good to be merged.

2024-12-20 11:32 UTC, antonpirker commented on sentry_sdk/_lru_cache.py
> +        while node is not self.root:
I have now put Anthony's implementation in this PR.

2024-12-20 11:33 UTC, antonpirker commented on sentry_sdk/_lru_cache.py
> +        return lru_cache
We opted for a different LRU implementation, so this discussion is for an outdated implementation and can be marked as resolved.

2024-12-20 11:34 UTC, merged

2024-12-20 15:08 UTC, cmanallen commented on sentry_sdk/_lru_cache.py
> +        return lru_cache
This is not resolved.  See https://github.com/getsentry/sentry-python/issues/3886