feat(flags): add Unleash feature flagging integration
getsentry/sentry-python pull request #3888
Opened 2024-12-21 02:00 UTC by aliu39

---

Thank you for contributing to `sentry-python`! Please add tests to validate your changes, and lint your code using `tox -e linters`.

Running the test suite on your PR might require maintainer approval. The AWS Lambda tests additionally require a maintainer to add a special label, and they will fail until this label is added.

2024-12-23 10:08 UTC, antonpirker commented
Hey @aliu39 ! Thanks for the integration. This will be reviewed after the holiday season.

2024-12-23 22:48 UTC, aliu39 commented
Todo:
- [x] verify w manual test
- [x] threading and asyncio tests
- [x] determine if [variant payload](https://docs.getunleash.io/reference/feature-toggle-variants#variant-payload) should factor into tracking (no, track every feature)
- [ ] docs w/ sample verification code

2025-01-06 17:25 UTC, cmanallen requested changes
Blocking this.  We're going to talk about how we handle this going forward and may close this.

2025-01-06 18:27 UTC, cmanallen approved these changes
Okay we're all good. We're going to keep this setup.

2025-01-07 14:12 UTC, antonpirker approved these changes
Looks good to me. 
Nice integrations, and GREAT test suite! Thanks for that!

2025-01-07 14:17 UTC, merged