Boto3 integration
getsentry/sentry-python pull request #896
Opened 2020-10-27 18:16 UTC by marshall-lee

This is the integration for boto3 library for recording requests to AWS services as spans.

Another suggestion is to enable it by default in `aws_lambda` integration since boto3 package is pre-installed on every lambda.

2020-10-27 19:10 UTC, untitaker requested changes
hi, this looks good! I added a review but after that I think we can merge

2020-10-27 19:10 UTC, untitaker commented on sentry_sdk/integrations/boto3.py
> +            def sentry_streaming_body_read(amt=None):
unless you need to interpret the arguments please use `*args, **kwargs` (in both read and close) to protect against api changes

2020-10-27 19:10 UTC, untitaker commented on sentry_sdk/integrations/boto3.py
> +            span = context.get("_sentrysdk_span")  # type: Optional[Span]
can we use context.pop in each function

2020-10-27 19:10 UTC, untitaker commented on sentry_sdk/integrations/boto3.py
> +            hub = Hub.current
Please add a `Hub.current.get_integration` check here like in other integrations to allow the integration to be disabled at a later point in time

2020-10-27 19:10 UTC, untitaker commented on tox.ini
>  deps =
I think you will have to add `boto3: boto3` (with a version constraint pls) here to make CI work

2020-10-28 19:21 UTC, untitaker commented on sentry_sdk/integrations/boto3.py
> +    span = context.pop("_sentrysdk_span")  # type: Optional[Span]
Ah please use `pop("...", None)` here, this should not throw

2020-10-28 19:21 UTC, untitaker approved these changes
one minor change then we can merge

2020-10-29 09:57 UTC, marshall-lee commented
@untitaker CI is green now!

2020-10-29 15:35 UTC, merged

2020-10-29 15:37 UTC, untitaker commented
Thanks! I think we should add integration docs like this one: https://docs.sentry.io/platforms/python/configuration/integrations/redis/